name: JiraPilot - Ollama Code Generation

on:
  repository_dispatch:
    types: [jira_branch_created]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Pull latest from main
      run: git pull origin main

    - name: Set up Python and dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install Ollama
      run: curl -fsSL https://ollama.com/install.sh | sh

    - name: Start Ollama server and pull model
      run: |
        ollama serve &
        sleep 5
        ollama pull gemma3:1b

    - name: Create unique feature branch
      id: branch
      run: |
        TICKET_KEY="${{ github.event.client_payload.ticket_key }}"
        BRANCH_BASENAME="feature/$TICKET_KEY"
        VERSION=1
        UNIQUE_BRANCH="$BRANCH_BASENAME"

        git fetch origin

        while git ls-remote --exit-code --heads origin "$UNIQUE_BRANCH" >/dev/null 2>&1; do
          UNIQUE_BRANCH="${BRANCH_BASENAME}_v$VERSION"
          VERSION=$((VERSION+1))
        done

        echo "branch_name=$UNIQUE_BRANCH" >> $GITHUB_OUTPUT
        echo "✅ Using branch: $UNIQUE_BRANCH"

    - name: Create and checkout feature branch
      run: |
        git checkout -b ${{ steps.branch.outputs.branch_name }}

    - name: Run code generation
      env:
        DESCRIPTION: "${{ github.event.client_payload.description }}"
        OLLAMA_MODEL: "gemma3:1b"
      run: |
        python3 code_generator.py "$DESCRIPTION"

    - name: Commit and push generated code
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        JIRA_TICKET_KEY: ${{ github.event.client_payload.ticket_key }}
      run: |
        git config user.name "abhishek singh"
        git config user.email "Abhishek11801529@gmail.com"

        git add .
        git commit -m "[${JIRA_TICKET_KEY}] Add generated code"
        git push origin ${{ steps.branch.outputs.branch_name }}
