name: JiraPilot - Ollama Code Generation

on:
  repository_dispatch:
    types: [jira_branch_created]  # Triggered by the Jira webhook

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the main branch
      uses: actions/checkout@v2
      with:
        ref: main  # Ensure we are starting with the latest main branch

    - name: Pull the latest main branch
      run: |
        git pull origin main  # Pull the latest changes from the main branch

    - name: Install dependencies
      run: |
        python3 -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate virtual environment
        pip install -r requirements.txt  # Install necessary Python dependencies

    - name: Install Ollama
      run: curl -fsSL https://ollama.com/install.sh | sh  # Install Ollama for LLM usage

    - name: Start Ollama Server and Pull Model
      run: |
        ollama serve &  # Run Ollama server in the background
        ollama pull gemma3:1b  # Pull the gemma:2b model

    - name: Run code generation with Ollama
      run: |
        python3 code_generator.py "${{ github.event.client_payload.description }}"  # Generate code based on description

    - name: Commit and push generated code to feature branch
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use the GitHub token to push changes
        JIRA_TICKET_KEY: ${{ github.event.client_payload.ticket_key }}  # Use Jira issue key
        FEATURE_BRANCH: ${{ github.event.client_payload.branch_name }}  # Feature branch name
      run: |
        # Configure git with the appropriate name and email
        git config --global user.name "Abhishek Singh"
        git config --global user.email "abhishek11801529@gmail.com"

        FEATURE_BRANCH="${{ github.event.client_payload.ticket_key }}"
        git checkout -b $FEATURE_BRANCH  # Create and checkout new feature branch based on the main branch
        git pull
        
        # Add the generated code file to the repository
        git add generated_code.py
        
        # Commit the generated code with the Jira issue key in the message
        git commit -m "[${{ env.JIRA_TICKET_KEY }}] Add generated code for prompt"
        
        # Push the changes to the feature branch
        git push origin $FEATURE_BRANCH
