name: JiraPilot - Ollama Code Generation

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Feature Branch Name'
        required: true
      ticket_key:
        description: 'Jira Ticket Key'
        required: true
      description:
        description: 'Description of code generation'
        required: true

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
    - name: Install Ollama
      run: curl -fsSL https://ollama.com/install.sh | sh

    - name: Run Ollama Server
      run: |
        ollama serve &  # Run Ollama server in the background
        ollama pull gemma3:1b  # Pull the model (you can change the model)

    - name: Install dependencies
      run: |
        python3 -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate virtual environment
        pip install -r requirements.txt  # Install necessary Python dependencies

    - name: Run code generation with Ollama
      run: |
        python3 code_generator.py "${{ github.event.inputs.description }}"  # Generate code based on description

    - name: Commit and push generated code to repo
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use the GitHub token to push changes
        JIRA_TICKET_KEY: ${{ github.event.inputs.ticket_key }}  # Use Jira issue key
        FEATURE_BRANCH: ${{ github.event.inputs.branch_name }}  # Feature branch name
      run: |
        # Configure git with the appropriate name and email
        git config --global user.name "Abhishek Singh"
        git config --global user.email "abhishek11801529@gmail.com"
        
        # Check out the feature branch
        git checkout $FEATURE_BRANCH
        
        # Add the generated code file to the repository
        git add generated_code.py
        
        # Commit the generated code with the Jira issue key in the message
        git commit -m "[${{ env.JIRA_TICKET_KEY }}] Add generated code for prompt"
        
        # Push the changes to the feature branch
        git push origin $FEATURE_BRANCH
