name: JiraPilot - Generate Code with Ollama

on:
  repository_dispatch:
    types: [jira_branch_created]

jobs:
  generate-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t jirapilot-codegen .

      - name: Run code generation (Ollama)
        run: |
          docker run --rm \
            -e DESCRIPTION="${{ github.event.client_payload.description }}" \
            -e OLLAMA_MODEL="gemma:2b" \
            -v ${{ github.workspace }}:/app \
            jirapilot-codegen

      - name: Commit & push code
        run: |
          git config user.name "jira-bot"
          git config user.email "jira-bot@example.com"
          git checkout -b "${{ github.event.client_payload.branch_name }}"
          git add .
          git commit -m "${{ github.event.client_payload.ticket_key }}-boilerplate"
          git push origin "${{ github.event.client_payload.branch_name }}"
